//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.sqlmodel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vueapiEntities1 : DbContext
    {
        public vueapiEntities1()
            : base("name=vueapiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<article> articles { get; set; }
        public virtual DbSet<article_message> article_message { get; set; }
        public virtual DbSet<message> messages { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<cart> carts { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<uermember> uermembers { get; set; }
        public virtual DbSet<buy> buys { get; set; }
        public virtual DbSet<test> tests { get; set; }
    }
}
